### ISSUE TITLE
Crash caused by Json::LogicError in network code

### ISSUE THREAD

**Issue by metalicjames** [mit-dci/CryptoKernel#57]
```
Wed Jul 18 22:17:10 2018 INFO Network(): Attempting to connect to 207.189.2.212
Wed Jul 18 22:17:13 2018 WARNING Network(): Failed to connect to 207.189.2.212
Wed Jul 18 22:17:13 2018 INFO Network(): Attempting to connect to 18.189.94.156
Wed Jul 18 22:17:13 2018 WARNING Network(): Failed to contact 10.42.0.1, disconnecting it for: peer didn't respond in time
terminate called after throwing an instance of 'Json::LogicError'
  what():  in Json::Value::setComment(): Comments must start with /

Thread 3 "ckd" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffef0d6700 (LWP 4495)]
0x00007ffff5643428 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
```

**Comment by metalicjames** [comment]
Backtrace:
```
Thu Jul 19 23:36:10 2018 WARNING Network(): Failed to connect to 207.189.30.233
Thu Jul 19 23:36:10 2018 INFO Network(): Attempting to connect to 18.110.158.28
Thu Jul 19 23:36:13 2018 WARNING Network(): Failed to connect to 18.110.158.28
Thu Jul 19 23:36:13 2018 INFO Network(): Attempting to connect to 207.189.2.228
Thu Jul 19 23:36:13 2018 WARNING Network(): Failed to contact 10.42.0.1, disconnecting it for: peer didn't respond in time
[Switching to Thread 0x7fffeef46700 (LWP 18769)]

Thread 3 "ckd" hit Catchpoint 1 (exception thrown), 0x00007ffff5f848bd in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) bt
#0  0x00007ffff5f848bd in __cxa_throw ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00007ffff70afdf7 in Json::throwLogicError(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
   from /usr/local/lib/libjsoncpp.so.19
#2  0x00007ffff70b0045 in Json::Value::CommentInfo::setComment(char const*, unsigned long) () from /usr/local/lib/libjsoncpp.so.19
#3  0x00007ffff70b61c6 in Json::Value::Value(Json::Value const&) ()
   from /usr/local/lib/libjsoncpp.so.19
#4  0x00007ffff70b8659 in std::_Rb_tree_node<std::pair<Json::Value::CZString const, Json::Value> >* std::_Rb_tree<Json::Value::CZString, std::pair<Json::Value::CZString const, Json::Value>, std::_Select1st<std::pair<Json::Value::CZString const, Json::Value> >, std::less<Json::Value::CZString>, std::allocator<std::pair<Json::Value::CZString const, Json::Value> > >::_M_copy<std::_Rb_tree<Json::Value::CZString, std::pair<Json::Value::CZString const, Json::Value>, std::_Select1st<std::pair<Json::Value::CZString const, Json::Value> >, std::less<Json::Value::CZString>, std::allocator<std::pair<Json::Value::CZString const, Json::Value> > >::_Alloc_node>(std::_Rb_tree_node<std::pair<Json::Value::CZString const, Json::Value> > const*, std::_Rb_tree_node<std::pair<Json::Value::CZString const, Json::Value> >*, std::_Rb_tree<Json::Value::CZString, std::pair<Json::Value::CZString const, Json::Value>, std::_Select1st<std::pair<Json::Value::CZString const, Json::Value> >, std::less<Json::Value::CZString>, std::allocator<std::pair<Json::Value::CZString const, Json::Value> > >::_Alloc_node&) ()
---Type <return> to continue, or q <return> to quit---
   from /usr/local/lib/libjsoncpp.so.19
#5  0x00007ffff70b868d in std::_Rb_tree_node<std::pair<Json::Value::CZString const, Json::Value> >* std::_Rb_tree<Json::Value::CZString, std::pair<Json::Value::CZString const, Json::Value>, std::_Select1st<std::pair<Json::Value::CZString const, Json::Value> >, std::less<Json::Value::CZString>, std::allocator<std::pair<Json::Value::CZString const, Json::Value> > >::_M_copy<std::_Rb_tree<Json::Value::CZString, std::pair<Json::Value::CZString const, Json::Value>, std::_Select1st<std::pair<Json::Value::CZString const, Json::Value> >, std::less<Json::Value::CZString>, std::allocator<std::pair<Json::Value::CZString const, Json::Value> > >::_Alloc_node>(std::_Rb_tree_node<std::pair<Json::Value::CZString const, Json::Value> > const*, std::_Rb_tree_node<std::pair<Json::Value::CZString const, Json::Value> >*, std::_Rb_tree<Json::Value::CZString, std::pair<Json::Value::CZString const, Json::Value>, std::_Select1st<std::pair<Json::Value::CZString const, Json::Value> >, std::less<Json::Value::CZString>, std::allocator<std::pair<Json::Value::CZString const, Json::Value> > >::_Alloc_node&) ()
   from /usr/local/lib/libjsoncpp.so.19
#6  0x00007ffff70b624d in Json::Value::Value(Json::Value const&) ()
   from /usr/local/lib/libjsoncpp.so.19
#7  0x000000000048a77e in CryptoKernel::Network::Connection::getCachedInfo (
    this=0x7fffe0000b10) at src/kernel/network.cpp:22
#8  CryptoKernel::Network::connectionFunc (this=<optimized out>)
    at src/kernel/network.cpp:608
#9  0x00007ffff5fafc80 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
---Type <return> to continue, or q <return> to quit---
#10 0x00007ffff64b76ba in start_thread (arg=0x7fffeef46700)
    at pthread_create.c:333
#11 0x00007ffff571541d in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb) 
```
